---
auditd_configuration_dict:
  - { keyword: 'max_log_file', argument: '6' }
  - { keyword: 'admin_space_left_action', argument: 'single' }
  - { keyword: 'max_log_file_action', argument: 'rotate' }

auditd_commands_b32_dict:
  - '-e 2'
  - '-a always,exit -F arch=b32 -S open,openat,open_by_handle_at,creat,truncate,ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access'
  - '-a always,exit -F arch=b32 -S open,openat,open_by_handle_at,creat,truncate,ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access'
  - '-w /usr/sbin/insmod -p x -k modules'
  - '-w /usr/sbin/rmmod -p x -k modules'
  - '-w /usr/sbin/modprobe -p x -k modules'
  - '-a always,exit -F arch=b32 -S init_module,delete_module -F key=modules'
  - '-w /var/log/tallylog -p wa -k logins'
  - '-w /var/run/faillock/ -p wa -k logins'
  - '-w /var/log/lastlog -p wa -k logins'
  - '-w /etc/localtime -p wa -k audit_time_rules'
  - '-a always,exit -F arch=b32 -S adjtimex,settimeofday,stime -F key=audit_time_rules'
  - '-a always,exit -F arch=b32 -S clock_settime -F a0=0x0 -F key=time-change'
  - '-a always,exit -F arch=b32 -S fchown,setxattr,fsetxattr,chown,lsetxattr,fchmodat,removexattr,fremovexattr,fchownat,fchmod,lremovexattr,chmod,lchown  -F auid>=1000 -F auid!=4294967295 -F key=perm_mod'
  - '-a always,exit -F arch=b32 -S rmdir,unlink,unlinkat,rename,renameat  -F auid>=1000 -F auid!=4294967295 -F key=delete'
  - '-w /etc/shadow -p wa -k audit_rules_usergroup_modification'
  - '-w /etc/gshadow -p wa -k audit_rules_usergroup_modification'
  - '-w /etc/passwd -p wa -k audit_rules_usergroup_modification'
  - '-w /etc/security/opasswd -p wa -k audit_rules_usergroup_modification'
  - '-w /etc/group -p wa -k audit_rules_usergroup_modification'
  - '-w /var/run/utmp -p wa -k session'
  - '-w /var/log/btmp -p wa -k session'
  - '-w /var/log/wtmp -p wa -k session'
  - '-a always,exit -F arch=b32 -S sethostname,setdomainname -F key=audit_rules_networkconfig_modification'
  - '-w /etc/issue -p wa -k audit_rules_networkconfig_modification'
  - '-w /etc/issue.net -p wa -k audit_rules_networkconfig_modification'
  - '-w /etc/hosts -p wa -k audit_rules_networkconfig_modification'
  - '-w /etc/sysconfig/network -p wa -k audit_rules_networkconfig_modification'
  - '-w /etc/sudoers -p wa -k actions'
  - '-w /etc/sudoers.d/ -p wa -k actions'
  - '-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -F key=export'
  - '-w /etc/selinux/ -p wa -k MAC-policy'

auditd_commands_b64_dict:
  - '-a always,exit -F arch=b64 -S open,openat,open_by_handle_at,creat,truncate,ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access'
  - '-a always,exit -F arch=b64 -S open,openat,open_by_handle_at,creat,truncate,ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access'
  - '-a always,exit -F arch=b64 -S init_module,delete_module -F key=modules'
  - '-a always,exit -F arch=b64 -S adjtimex,settimeofday -F key=audit_time_rules'
  - '-a always,exit -F arch=b64 -S clock_settime -F a0=0x0 -F key=time-change'
  - '-a always,exit -F arch=b64 -S fchown,setxattr,fsetxattr,chown,lsetxattr,fchmodat,removexattr,fremovexattr,fchownat,fchmod,lremovexattr,chmod,lchown  -F auid>=1000 -F auid!=4294967295 -F key=perm_mod'  
  - '-a always,exit -F arch=b64 -S rmdir,unlink,unlinkat,rename,renameat  -F auid>=1000 -F auid!=4294967295 -F key=delete'
  - '-a always,exit -F arch=b64 -S sethostname,setdomainname -F key=audit_rules_networkconfig_modification'
  - '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -F key=export'